### ISSUE TITLE
Issue with Helm chart using secrets that already exist in the cluster

### ISSUE THREAD

**Issue by tcaddy** [port-labs/ocean#1463]
### Ocean Framework Version

Version `0.7.0` of the helm chart for the `port-ocean` integration.

### Integration Version

Version `0.7.0` of the helm chart for the `port-ocean` integration.

### Steps to reproduce

Put the secrets in place in the target namespace in the target cluster with the exact same name of the secret and payload of the `data` attribute that the Port integration would need to work.  Do this prior to helm chart install.

Install helm chart with these values (argocd integration for example).  Notice how I'm not specifying any values that would become secrets on a helm install:
```yaml
port:
  baseUrl: https://api.getport.io
initializePortResources: true
sendRawDataExamples: true
scheduledResyncInterval: 360
secret:
  create: false
  useExistingSecret: true
integration:
  identifier: argocd
  type: argocd
  config:
    serverUrl: https://argocd.argoproj.io
  eventListener:
    type: POLLING
```

### What did you expect to see?

I expect to see the YAML for the deployment still use these secrets and thus have the expected environment variables present in the deployment so the application runs

### What did you see instead?

The application does a crash loop backoff with logs complaining about missing secrets.

When I look at the YAML for the deployment, I would expect to see `envFrom` reference the secret or to see a secretRef to each expected secret, but it isn't there.

When I look at the template for the Helm chart (my first time seeing a helm template :barf:), I see this:
```
{{- define "port-ocean.additionalSecrets" }}
{{- $secretsArray := list }}
{{- if or .Values.secret.create .Values.secret.name }}
  {{- $secretsArray = list (include "port-ocean.secretName" .) }}
{{- end }}
{{- /* If the secretName is already an array we don't wrap it in an array */}}
{{- if kindIs "slice" .Values.secret.name }}
  {{- $secretsArray = .Values.secret.name }}
{{- end }}
{{- range $secretsArray }}
- secretRef:
    name: {{ . }}
{{- end }}
{{- end }}
```

I don't think the logic is correct in the helm chart b/c the deployment yaml should still referencing the expected secrets

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!
