### ISSUE TITLE
[Enhancement/Feature] [Framework] Allow ingesting values in Port based on CI/CD variables values

### ISSUE THREAD

**Issue by Mivr** [port-labs/ocean#556]
### Motivation

We are using the GitLab ingestion of data, and we stumbled upon a use case where we want to use the value of a CI/CD variable while ingesting data into Port.

For us, the use case is that we store a key for the project in another system in CI/CD variables that are standardized in all projects, and we want to extract this key so that we can automatically connect the GitLab project and the other system project.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Tankilevitch** [comment]
Hey @Mivr 👋 
If I understand correctly, you have some parameter which is coming from outside, which you want to use to be able to map between entity relations.

If that is the case, we already support it through the JQ library. 
You can pass environment variables to the application and use them in your integration mapping. 

here you can see an example, notice the last mapping param. [env](https://jqlang.github.io/jq/manual/#$env-env) is a built-in method inside JQ that allows you to use environment variables. In my example I've just queried some available env, but you can combine it with whatever you need.

```
resources:
  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .path_with_namespace | gsub(" "; "")
          title: .name
          blueprint: '"service"'
          properties:
            url: .web_url
            readme: file://README.md
            description: .description
            language: .__languages | to_entries | max_by(.value) | .key
            env: env | .APPLICATION__LOG_LEVEL
```  

Let me know if that works for you 🙏
