### ISSUE TITLE
[Enhancement/Feature] [Integration] [argoCD] : allow for Cluster name override

### ISSUE THREAD

**Issue by sgandon** [port-labs/ocean#594]
### Motivation

We are using argoCD in an embedded mode, that means we have an instance of ArgoCD running in each of our clusters.
each cluster définition comes with `name` and a `server` values.
<img width="884" alt="image" src="https://github.com/port-labs/ocean/assets/783286/79ecd63c-ceba-4d1d-a6ee-b22a226f60b5">
The server value is always the same as it is internal to the cluster but the cluster name changes in order to be able to identify it.
The current integration uses the `api/v1/applications` api to list all applications and uses [the cluster name](https://github.com/port-labs/ocean/blob/e8f377ca9a1e49d84be4eb705bef591d54a33c4f/integrations/argocd/.port/resources/port-app-config.yaml#L67) to link the app to a cluster.
Unfortunately the API does not returns the cluster `name`, see [the issue](https://github.com/argoproj/argo-cd/issues/18009) I created on argoCD side.

### Proposed Changes

Would it be possible to allow an override of cluster name in the integration to work around that issue ?
Adding a new config for the user to specify the cluster name.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Tankilevitch** [comment]
Hey @sgandon 👋🏼 nice meeting you glad to see you are using the ArgoCD integration 🤩

Can you please elaborate on how you installed your ocean ArgoCD integration, as I am less familiar with the embedded mode.
Is it still one installation per all of your clusters or one per cluster due to the embedded behavior?

If it's one per cluster, you can just add the cluster prefix to the mapping configuration of each integration through the UI. 

cluster: "prod-cluster"

If it's still one installation for all of the cluster then I am not quite sure how you want to use the override inside the code.

**Comment by sgandon** [comment]
Hello @Tankilevitch,
ArgoCD services are installed in each of our clusters.
For the Port integration I create a single Data source and since I am just doind tests I launched the docker image integration locally but eventually this shall be installed as a pod in our cluster.
For my test I worked around the issue by doing exactly what you suggested and hardcoded the cluster name in the port mapping.
But I don't want to create a new port data source for each of my clusters (too many) and override them all with each cluster name.
I'd rather have a way on the ocean process to override the cluster name. That way I'll have one single data source of argoCD on Port side otherwise I'll have to duplicate all mapping changes I need to be doing for all argocd datasources.

**Comment by Tankilevitch** [comment]
Hey @sgandon .
Thanks for clarifying 🙏 

Eventually ocean is running jq to process the entities, so if you want to keep the same mapping for all datasources you can configure an environment variable for each of the installations and use it inside the JQ. 

```
resources:
  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .path_with_namespace | gsub(" "; "")
          title: .name
          blueprint: '"service"'
          properties:
            url: .web_url
            readme: file://README.md
            description: .description
            language: .__languages | to_entries | max_by(.value) | .key
            cluster: env | .CLUSTER_NAME
```
for more information see this issue thread - https://github.com/port-labs/ocean/issues/556#issuecomment-2061275926 

I have also created a canny feature request about your use case, so feel free to upvote and leave a comment.
